name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at 00:00 UTC
  workflow_dispatch:     # lets you run it manually from Actions tab

permissions:
  contents: write        # allow this workflow to push to the repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Pacman contribution graph
        uses: Platane/snk@v3
        with:
          github_user_name: shabiul
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg

      - name: Commit and push SVG files
        uses: EndBug/add-and-commit@v9
        with:
          add: "output"
          message: "chore: update pacman contribution graph"
